### PR TITLE
Support `Parser::Ruby28`

### PR DESCRIPTION
**Pull request by koic**
Parser gem has been started development for Ruby 2.8 (edge Ruby).
https://github.com/whitequark/parser/pull/677

This PR supports `Parser::Ruby28`, the early adapters will be able to try edge Ruby with RuboCop.

I will open a PR later to new Ruby 2.8 (3.0) syntax supported by Parser.

### CODE REVIEW

**Comment by marcandre** [comment]
👍 😄

**Comment by bbatsov** [comment]
I guess we need to cut a new `rubocop-ast` release now.

**Comment by marcandre** [comment]
I can take care of it. Let me merge #35.
Maybe we could include #29 too...

**Comment by marcandre** [comment]
I'll also add a note that 2.8 support is experimental until that version is actually released.

**Comment by marcandre** [comment]
`v0.1.0` released 🎉

**Pull request merged**
