### PR TITLE
Remove `:rasgn` and `:mrasgn` types.

### PR DESCRIPTION
**Pull request by marcandre**
See https://github.com/whitequark/parser/pull/739

### CODE REVIEW

**Comment by marcandre** [comment]
@eregon Test runs hang on `truffleruby` (second time in a row). I stopped last run after 5 hours (I'm surprised github actions doesn't seem to have a cutoff?)

**Comment by eregon** [comment]
It's possible to specify a timeout for GitHub Actions:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

I'll try to reproduce. It seems to only affect `truffleruby-head`, right?

**Comment by eregon** [comment]
It gets stuck in
https://github.com/rubocop-hq/rubocop-ast/blob/2788a1a0e129013f7e401a52b03a916b8dd0d495/lib/rubocop/ast/node_pattern/node.rb#L200-L204
Unfortunate that GitHub Actions doesn't send SIGINT or so, it would have shown that clearly.

TruffleRuby recently updated to 2.7, but didn't port that fix yet.

**Comment by eregon** [comment]
This is quite involved because I had to finish writing a spec for Range#minmax, synchronize specs across implementations and then actually fix it in TruffleRuby.

**Comment by eregon** [comment]
BTW, is there any reason not to use `Range#begin/end` here? It's always very fragile to depends on `RUBY_VERSION` checks.

**Comment by marcandre** [comment]
Thanks for the investigation!

> is there any reason not to simply use `Range#begin/end` here

I don't remember, and it looks like all the arity ranges are inclusive, so maybe not. Still, I'd rather write things properly; also I should probably be using refinements here. Does `map(&:refined_method)` work in truffleruby?

>  It's very fragile to depend on `RUBY_VERSION` checks.

Agreed, it's also not the best in general. I think I can use a different check like `(0..4.2).minmax.last`

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/df78798c151e87ae79e1e882cb5c64f70e01d1e6, thanks for the ping.
So no need to change anything :)

> I don't remember, and it looks like all the arity ranges are inclusive, so maybe not.

Exclusive ranges wouldn't work anyway, 2.7.2:
```
> (0...Float::INFINITY).minmax
TypeError: cannot exclude non Integer end value
```

> Does map(&:refined_method) work in truffleruby?

It does. But implementation-wise, that's a proper nightmare (need to cache globally per execution context & per refinements), I'd recommend having an explicit block.

**Comment by marcandre** [comment]
> Fixed in [oracle/truffleruby@df78798](https://github.com/oracle/truffleruby/commit/df78798c151e87ae79e1e882cb5c64f70e01d1e6), thanks for the ping.
> So no need to change anything :)
> 
> > I don't remember, and it looks like all the arity ranges are inclusive, so maybe not.
> 
> Exclusive ranges wouldn't work anyway, 2.7.2:

Right. For `parser`'s TreeRewriter, I break the integers into exclusive integer ranges and a last inifnite range (that I make inclusive because it doesn't work otherwise, but I think that's unfortunate): `0...15, 15...42, 42..Float::INFINITY`. Works like a charm.

> > Does map(&:refined_method) work in truffleruby?
> 
> It does. But implementation-wise, that's a proper nightmare (need to cache globally per execution context & per refinements), I'd recommend having an explicit block.

Ok. Since TruffleRuby is fixed now, I could use a conditional refinement here to support MRI <= 2.6. Should be nicer.

**Pull request merged**
