### PR TITLE
Add Node#left_sibling, right_sibling, left_siblings and right_siblings

### PR DESCRIPTION
**Pull request by marcandre**
[Requested](https://github.com/rubocop-hq/rubocop/pull/8474#discussion_r466959357) by @fatkodima

### CODE REVIEW

**Comment by fatkodima** [comment]
👍 
I think, just `siblings` may also be useful too.

**Comment by marcandre** [comment]
> 👍
> I think, just `siblings` may also be useful too.

as in `left_siblings + right_siblings`?

**Comment by fatkodima** [comment]
Haven't find any, but maybe, mayyybeee (😄 ) it will be needed in the future.

**Comment by marcandre** [comment]
So I merged this, if we see a lot of `left_siblings + right_siblings`, we'll add `siblings`...

**Pull request merged**
