### PR TITLE
Fix `#value` for a `dstr` node.

### PR DESCRIPTION
**Pull request by dvandersluis**
`dstr` nodes previously used `StrNode`, which exposes `#value`; however, it just returns the first child, which is a node, not a string value.

This changes `dstr`s to have their own node class that inherits from `StrNode`  but overrides `#value` as to get the actual  string value of the node (including any interpolations).

ie.
```ruby
'foo' \
'bar'

# previously:
dstr_node.value => s(:str, "foo")

# after change:
dstr_node.value => 'foobar'
```

### CODE REVIEW

**Comment by marcandre** [comment]
Seems like a good addition. Would you add a Changelog entry (same way as the main gem) please?

**Comment by dvandersluis** [comment]
Definitely!

**Comment by marcandre** [comment]
Still can't see it...

**Comment by dvandersluis** [comment]
@marcandre updated now!

**Comment by marcandre** [comment]
Thanks!
Released 1.4.1

**Comment by tas50** [comment]
@dvandersluis Thanks for fixing this. I had actually been working around it.

**Pull request merged**
