### PR TITLE
Add RegexpNode regopt predicates

### PR DESCRIPTION
**Pull request by owst**
As suggested by @bbatsov here:
  https://github.com/rubocop-hq/rubocop/pull/8073#discussion_r433131081

### CODE REVIEW

**Comment by marcandre** [comment]
Looks great!
Would you also add the "o" option please?

**Comment by owst** [comment]
Oops - accidental omission, thanks @marcandre !

I've never used the `o` option before, and I struggled to find an example where it causes a change in behaviour. I finally came up with:
```
[1] pry(main)> Array.new(3) { |i| /#{i}/ }
=> [/0/, /1/, /2/]
[2] pry(main)> Array.new(3) { |i| /#{i}/o }
=> [/0/, /0/, /0/]
```
even then, I'm not sure when this would be useful! 

The Perl [docs say](https://perldoc.perl.org/perlre.html#Other-Modifiers):
>   o  - pretend to optimize your code, but actually introduce bugs

😄

**Comment by bbatsov** [comment]
Thanks!

**Comment by marcandre** [comment]
Oh, that actually breaks `RuboCop`. Probably a naming conflict with `multiline?`. I'm reopening #5

**Comment by owst** [comment]
Good catch @marcandre and 👍 for running RuboCop specs too

**Pull request merged**
